project:
  type: website
  output-dir: docs

website:
  title: "Mouse.games!"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - about.qmd
      - href: games.qmd
        text: Games

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



